# Generated by Django 2.2.4 on 2019-09-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tittle',
            new_name='title',
        ),
    ]
